import Head from 'next/head';
import { useEffect } from 'react';
import styles from '../styles/Home.module.css';
import Navigation from '../components/Navigation/Navigation';
import Hero from '../components/Hero/Hero';
import History from '../components/HIstory/History';
import Service from '../components/OurService/Service';
import ServiceContact from '../components/OurService/ServiceContact';
import WhyUs from '../components/WhyUs/WhyUs';
import Contact from '../components/WhyUs/Contact';
import Aos from 'aos';
import 'aos/dist/aos.css';
import { Html } from 'next/document';

export default function Home() {
  useEffect(() => {
    Aos.init({ duration: 1000 });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Hero />
      <History />
      <Service />
      <ServiceContact />
      <WhyUs />
      <Contact />
    </div>
  );
}
